### PR TITLE
Added seed data for Order table, and added an attribute (Purchased) t…

### PR DESCRIPTION
**Pull request by lewiskg**
…o the Order table.

### CODE REVIEW

**Comment by hagansmith** [comment]
Don't see the update script for the order table to add the row purchased. I just see the seed data.

**Comment by lewiskg** [comment]
Thanks for catching the missing file, Adam.  I have modified my pull request to include the missing master sql file with the updated Order table.

**Comment by hagansmith** [comment]
Need to add the lines below to drop the existing DB at the top under the USE [master]
GO

DROP DATABASE [SNQHM_bangazoncli_db]
GO
------ NOTE TO All-----
Once the DB has been rebuilt seed data will need to be added in the following Sequence:
Customer Table
Product Table
Payment Table
Order (the Payment ids may not match so check your DB if you get an error with the foreign key constraint)

**Comment by hagansmith** [comment]
Also we are getting your .DS_Store files from working on your Mac can you add that to the gitignore as part of this PR.

**Pull request merged**
